const data = {
  products: {
    pizzas: {
      grande: [{
        id: 'G1',
        name: 'Americana',
        description: 'Delicioso jamón y queso mozzarella',
        price: '40.90',
        detail: 'Pizza Americana Grande a S/40.90',
        image: 'images/pizzas/Americana.png',
      },
      {
        id: 'G2',
        name: 'Pepperoni',
        description: 'Delicioso pepperoni y queso mozzarella',
        price: '40.90',
        detail: 'Pizza Pepperoni Grande a S/40.90',
        image: 'images/pizzas/pepperoni.jpg',
      },
      {
        id: 'G3',
        name: 'Mozarella',
        description: 'Queso mozzarella extra',
        price: '40.90',
        detail: 'Pizza Mozarella Grande a S/40.90',
        image: 'images/pizzas/mozarella.jpg',
      },

      {
        id: 'G4',
        name: 'Vegetariana',
        description: 'Tomates, champiñones, cebolla, pimientos, aceitunas negras y queso mozzarella',
        price: '40.90',
        detail: 'Pizza Vegetariana Grande a S/40.90',
        image: 'images/pizzas/vegetariana.jpg',
      },
      {
        id: 'G5',
        name: 'Hawaiana',
        description: 'Delicioso jamón, refrescante piña y riquísimo queso mozzarella extra',
        price: '45.90',
        detail: 'Pizza Hawaiana Grande a S/45.90',
        image: 'images/pizzas/hawaiana.jpg',
      },
      {
        id: 'G6',
        name: 'Continentalle',
        description: 'Jamón, cebolla, champiñones y queso mozarella',
        price: '45.90',
        detail: 'Pizza Continentalle Grande a S/45.90',
        image: 'images/pizzas/continentalle.jpg',
      },
      {
        id: 'G7',
        name: 'Española',
        description: 'Chorizo, cebolla blanca, aceitunas verdes, aceitunas negras, champiñones, queso mozzarella y salsa de ajo en el fondoDelicioso jamón, refrescante piña y riquísimo queso mozzarella extra',
        price: '45.90',
        detail: 'Pizza Española Grande a S/45.90',
        image: 'images/pizzas/española.png',
      },
      {
        id: 'G8',
        name: 'Veggie Delight',
        description: 'Salsa Cremosa Espinaca Alfredo en la base, queso mozzarella, cebollas y champiñones',
        price: '45.90',
        detail: 'Pizza Veggie Delight Grande a S/45.90',
        image: 'images/pizzas/veggie-delight.png',
      },
      {
        id: 'G9',
        name: 'The Works',
        description: 'Pepperoni, salchicha italiana, jamón, pimientos verdes, cebolla blanca, champiñones, aceitunas negras y queso mozzarella',
        price: '55.90',
        detail: 'Pizza The Works Grande a S/55.90',
        image: 'images/pizzas/the-works.jpg',
      },
      {
        id: 'G10',
        name: 'All the Meats',
        description: 'Pepperoni, salchicha de cerdo, jamón, tocino, carne de res y queso mozzarella',
        price: '55.90',
        detail: 'Pizza All the Meats Grande a S/55.90',
        image: 'images/pizzas/all-the-meats.jpg',
      },
      {
        id: 'G11',
        name: 'Hawaiian Chicken BBQ',
        description: 'Deliciosa base de salsa BBQ, pollo, tocino, cebolla blanca, piña y queso mozzarella',
        price: '55.90',
        detail: 'Pizza Hawaiian Chicken BBQ Grande a S/55.90',
        image: 'images/pizzas/hawaiianBBQ.jpg',
      },
      {
        id: 'G12',
        name: 'Sicilian Meats',
        description: 'Salame, chorizo, salchicha italiana, pepperoni y queso mozzarella',
        price: '55.90',
        detail: 'Pizza Sicilian Meats Grande a S/55.90',
        image: 'images/pizzas/sicilian-meats.jpg',
      },
      {
        id: 'G13',
        name: 'Chicken BBQ',
        description: 'Pollo, tocino, cebolla blanca, queso mozzarella y de base la salsa barbacoa inigualable',
        price: '55.90',
        detail: 'Pizza Chicken BBQ Grande a S/55.90',
        image: 'images/pizzas/Chicken-BBQ.png',
      },
      {
        id: 'G14',
        name: 'La Favorita de John',
        description: '6 tipo de quesos,  salchicha, pepperoni y especias italianas',
        price: '55.90',
        detail: 'Pizza La Favorita de John Grande a S/55.90',
        image: 'images/pizzas/la-favorita-john.jpg',
      },

      ],
      familiar: [{
        id: 'F1',
        name: 'Americana',
        description: 'Delicioso jamón y queso mozzarella',
        price: '50.90',
        detail: 'Pizza Americana Familiar a S/50.90',
        image: 'images/pizzas/Americana.png',
      },
      {
        id: 'F2',
        name: 'Pepperoni',
        description: 'Delicioso pepperoni y queso mozzarella',
        price: '50.90',
        detail: 'Pizza Pepperoni Familiar a S/50.90',
        image: 'images/pizzas/pepperoni.jpg',
      },
      {
        id: 'F3',
        name: 'Mozarella',
        description: 'Queso mozzarella extra',
        price: '50.90',
        detail: 'Pizza Mozarella Familiar a S/50.90',
        image: 'images/pizzas/mozarella.jpg',
      },
      {
        id: 'F4',
        name: 'Vegetariana',
        description: 'Tomates, champiñones, cebolla, pimientos, aceitunas negras y queso mozzarella',
        price: '50.90',
        detail: 'Pizza Vegetariana Familiar a S/50.90',
        image: 'images/pizzas/vegetariana.jpg',
      },
      {
        id: 'F5',
        name: 'Hawaiana',
        description: 'Delicioso jamón, refrescante piña y riquísimo queso mozzarella extra',
        price: '55.90',
        detail: 'Pizza Hawaiana Familiar a S/55.90',
        image: 'images/pizzas/hawaiana.jpg',
      },
      {
        id: 'F6',
        name: 'Continentalle',
        description: 'Jamón, cebolla, champiñones y queso mozarella',
        price: '55.90',
        detail: 'Pizza Continentalle Familiar a S/55.90',
        image: 'images/pizzas/continentalle.jpg',
      },
      {
        id: 'F7',
        name: 'Española',
        description: 'Chorizo, cebolla blanca, aceitunas verdes, aceitunas negras, champiñones, queso mozzarella y salsa de ajo en el fondoDelicioso jamón, refrescante piña y riquísimo queso mozzarella extra',
        price: '55.90',
        detail: 'Pizza Española Familiar a S/55.90',
        image: 'images/pizzas/española.png',
      },
      {
        id: 'F8',
        name: 'Veggie Delight',
        description: 'Salsa Cremosa Espinaca Alfredo en la base, queso mozzarella, cebollas y champiñones',
        price: '55.90',
        detail: 'Pizza Veggie Delight Familiar a S/55.90',
        image: 'images/pizzas/veggie-delight.png',
      },
      {
        id: 'F9',
        name: 'The Works',
        description: 'Pepperoni, salchicha italiana, jamón, pimientos verdes, cebolla blanca, champiñones, aceitunas negras y queso mozzarella',
        price: '65.90',
        detail: 'Pizza The Works Familiar a S/65.90',
        image: 'images/pizzas/the-works.jpg',
      },
      {
        id: 'F10',
        name: 'All the Meats',
        description: 'Pepperoni, salchicha de cerdo, jamón, tocino, carne de res y queso mozzarella',
        price: '65.90',
        detail: 'Pizza All the Meats Familiar a S/65.90',
        image: 'images/pizzas/all-the-meats.jpg',
      },
      {
        id: 'F11',
        name: 'Hawaiian Chicken BBQ',
        description: 'Deliciosa base de salsa BBQ, pollo, tocino, cebolla blanca, piña y queso mozzarella',
        price: '65.90',
        detail: 'Pizza Hawaiian Chicken BBQ Familiar a S/65.90',
        image: 'images/pizzas/hawaiianBBQ.jpg',
      },
      {
        id: 'F12',
        name: 'Sicilian Meats',
        description: 'Salame, chorizo, salchicha italiana, pepperoni y queso mozzarella',
        price: '65.90',
        detail: 'Pizza Sicilian Meats Familiar a S/65.90',
        image: 'images/pizzas/sicilian-meats.jpg',
      },
      {
        id: 'F13',
        name: 'Chicken BBQ',
        description: 'Pollo, tocino, cebolla blanca, queso mozzarella y de base la salsa barbacoa inigualable',
        price: '65.90',
        detail: 'Pizza Chicken BBQ Familiar a S/65.90',
        image: 'images/pizzas/Chicken-BBQ.png',
      },
      {
        id: 'F14',
        name: 'La Favorita de John',
        description: '6 tipo de quesos,  salchicha, pepperoni y especias italianas',
        price: '65.90',
        detail: 'Pizza La Favorita de John Familiar a S/65.90',
        image: 'images/pizzas/la-favorita-john.jpg',
      },

      ],
    },
    adicionales: [{
      id: 'A1',
      name: 'Pepperoni Rolls',
      description: '6 riquísimos rolls de pepperoni enrollados con nuestra masa especial',
      price: '10.90',
      detail: 'Pepperoni rolls a S/ 10.90',
      image: 'images/adicionales/rolls-pepperoni.jpg',
    },
    {
      id: 'A2',
      name: 'Rolls de Jamón',
      description: '6 riquísimos rolls de jamón enrollados con nuestra masa especial.',
      price: '10.90',
      detail: 'Rolls de Jamón a S/ 10.90',
      image: 'images/adicionales/rolls-jamon.jpg',
    },
    
    {
      id: 'A3',
      name: 'Stuffed Chessesticks',
      description: '6 Deliciosos palitos rellenos de 6 quesos, cubiertos con nuestra inigualable Salsa Garlic con un toque especial de tocino ahumado.',
      price: '14.90',
      detail: 'Stuffed Chessesticks a S/ 14.90',
      image: 'images/adicionales/Stuffed-Chessesticks.png',
    },

    {
      id: 'A4',
      name: 'Palitos de Ajo Parmesano',
      description: 'Masa fresca recién horneada, cubierta con nuestra salsa de ajo y sazonados con queso parmesano y especias italianas.',
      price: '10.90',
      detail: 'Palitos de Ajo Parmesano a S/ 15.90',
      image: 'images/adicionales/palitos-ajo.jpg',
    },
    {
      id: 'A5',
      name: 'Chicken Poppers',
      description: '8 Deliciosos trocitos de pechuga de pollo ligeramente empanizados, cocinados al horno y acompañados de tu salsa favorita.',
      price: '15.90',
      detail: 'Chicken Poppers a S/ 15.90',
      image: 'images/adicionales/chicken-poppers.jpg',
    }

    

    ],
    bebidas: [{
      id: 'B1',
      name: 'Coca Cola',
      description: 'Coca Cola sabor original de 1,5L',
      price: '7.90',
      detail: 'Coca Cola Original a S/ 7.90',
      image: 'images/bebidas/CC-original.png',
    },
    {
      id: 'B2',
      name: 'Inca Kola',
      description: 'Inca Kola sabor original de 1,5L',
      price: '7.90',
      detail: 'Inca Kola Original a S/ 7.90',
      image: 'images/bebidas/Logo-IK-original.png',
    },
    {
      id: 'B3',
      name: 'Coca Cola sin Azúcar',
      description: 'Coca Cola sin azúcar de 1,5L',
      price: '7.90',
      detail: 'Coca Cola sin azúcar a S/ 7.90',
      image: 'images/bebidas/CC-sin-azucar.png',
    },
    {
      id: 'B4',
      name: 'Inca Kola sin Azúcar ',
      description: 'Inca Kola sin azúcar de 1,5L',
      price: ' 7.90',
      detail: 'Inca Kola sin azúcar a S/ 7.90',
      image: 'images/bebidas/Logo-IK-sin-azucar.png',
    },
    {
      id: 'B5',
      name: 'Coca Cola',
      description: 'Coca Cola sabor original personal',
      price: '3.90',
      detail: 'Coca Cola Original a S/ 3.90',
      image: 'images/bebidas/CC-original.png',
    },
    {
      id: 'B6',
      name: 'Inca Kola',
      description: 'Inca Kola sabor original personal',
      price: '3.90',
      detail: 'Inca Kola Original a S/ 3.90',
      image: 'images/bebidas/Logo-IK-original.png',
    },
    {
      id: 'B7',
      name: 'Coca Cola sin Azúcar',
      description: 'Coca Cola sin azúcar personal',
      price: '3.90',
      detail: 'Coca Cola sin azúcar a S/ 3.90',
      image: 'images/bebidas/CC-sin-azucar.png',
    },
    {
      id: 'B8',
      name: 'Inca Kola sin Azúcar ',
      description: 'Inca Kola sin azúcar personal',
      price: ' 3.90',
      detail: 'Inca Kola sin azúcar a S/ 3.90',
      image: 'images/bebidas/Logo-IK-sin-azucar.png',
    },

    {
      id: 'B9',
      name: 'Fanta  Zero  Azúcar',
      description: 'Fanta Zero Azúcar personal',
      price: '3.90',
      detail: 'Fanta Zero Azúcar a S/ 3.90',
      image: 'images/bebidas/Logo-Fanta-Zero-Azucar.png',
    },
    {
      id: 'B10',
      name: 'Sprite Zero Azúcar',
      description: 'Sprite Zero Azúcar personal',
      price: '3.90',
      detail: 'Sprite Zero Azúcar a S/ 3.90',
      image: 'images/bebidas/Logo-Sprite-Zero-Azucar.png',
    },
    ],
    postres: [{
      id: 'P1',
      name: 'Cinnamon Rolls',
      description: '6 riquísimos rolls enrollados con dulce de canela, cubiertos con azúcar glaseada.',
      price: '9.90',
      detail: 'Cinnamon Rolls a S/ 9.90',
      image: 'images/postres/cinnamonrolls.jpg',
    }
    

    ],
    extras: [{
      id: 'E1',
      name: 'Pepperoncini',
      description: '4 Deliciosos pimientos picantes traídos de Grecia y Turkía.',
      price: '1.00',
      detail: 'Pepperoncini a S/ 1.00',
      image: 'images/extras/pepperoncini.jpg',

    },
    {
      id: 'E2',
      name: 'Salsa BBQ',
      description: 'Dulce, famosa, exquisita y deliciosa salsa BBQ.',
      price: '1.00',
      detail: 'Salsa BBQ a S/ 1.00',
      image: 'images/extras/Barbeque.png',

    },
    {
      id: 'E3',
      name: 'Salsa Buffalo',
      description: 'Exquisita Salsa Buffalo. Disfruta de su picante único a solo S/1.00.',
      price: '1.00',
      detail: 'Salsa Buffalo a S/ 1.00',
      image: 'images/extras/Buffalo.png',

    },
    {
      id: 'E4',
      name: 'Salsa Garlic',
      description: 'Deliciosa salsa Garlic para disfrutar de forma sin igual el borde de tu pizza.',
      price: '1.00',
      detail: 'Salsa Garlic a S/ 1.00',
      image: 'images/extras/garlicsauce.jpg',

    },

    ],

  },
};


